on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp-arcadiazooecf.alwaysdata.net
        username: arcadiazooecf
        password: ${{ secrets.ftp_password }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/bootstrap/scss/**
          **/node_modules/bootstrap-icons/icons/**
        #protocol: ftps
        #port: 21
        #passive: true  # Enable passive mode
        server-dir: /www/
        #concurrency: 1 # Set to 1 to limit parallel connections
        #timeBetweenConnections: 1000 # 1 second delay between connections
        
